// src/services/vulnSeed.js
// Local, frontend-only stand-in for the backend's vulnerability seed
// (backend/app/features/vulnerabilities/repository.py _SEED), scored with
// scoringEngine.js. Used so the app can run with no backend at all — see
// api/client.js's getVulnerabilities(), which falls back to this when the
// API is unreachable. Keep the rows in sync with the backend seed if that
// changes; this is a copy, not a shared source of truth.
import { scoreVulnerability } from './scoringEngine';

const RAW = [
  // ── Direct: asset-mapped CVEs ────────────────────────────────────────────
  { vuln_id:'V-1001', title:'Unauthenticated command injection in PLC firmware',
    asset_label:'PLC-CTRL-01', assets:['PLC-CTRL-01'],
    cvss:9.6, epss:0.74, in_kev:true, cwe:'CWE-77', cpe:'cpe:2.3:o:vendor:plc_fw:*',
    cve_id:'CVE-2023-44317', tech:'PLC', zones:['Z-CTRL'],
    relevance_type:'Direct', implemented_sl:1, target_sl:3,
    observed_conn:3, allowed_conn:2, purdue_adjacency:1, log_backed:true,
    description:'Unauthenticated attacker can inject controller commands over the control protocol.',
    source:'ai', ai_confidence:94, status:'Open' },
  { vuln_id:'V-1002', title:'Outdated SCADA server operating system',
    asset_label:'SCADA-SRV-01', assets:['SCADA-SRV-01'],
    cvss:9.3, epss:0.41, in_kev:true, cwe:'CWE-1104', cve_id:'CVE-2023-0413',
    tech:'SCADA', zones:['Z-OPS'], relevance_type:'Direct',
    implemented_sl:2, target_sl:3, observed_conn:2, allowed_conn:2, purdue_adjacency:1, log_backed:true,
    description:'Unsupported OS with publicly available exploits.', source:'ai', ai_confidence:88, status:'Open' },
  { vuln_id:'V-1003', title:'Default vendor credentials on HMI',
    asset_label:'HMI-OPS-01', assets:['HMI-OPS-01'],
    cvss:9.4, epss:0.22, in_kev:false, cwe:'CWE-798', cve_id:'CVE-2022-38765',
    tech:'HMI', zones:['Z-CTRL'], relevance_type:'Direct',
    implemented_sl:2, target_sl:3, observed_conn:1, allowed_conn:1, purdue_adjacency:1, log_backed:true,
    description:'Shipped administrative credentials remain active.', source:'ai', ai_confidence:65, status:'Open' },
  { vuln_id:'V-1004', title:'RCE via RDP on engineering workstation',
    asset_label:'ENG-WS-01', assets:['ENG-WS-01'],
    cvss:8.2, epss:0.66, in_kev:true, cwe:'CWE-416', cve_id:'CVE-2019-0708',
    tech:'Engineering workstation', zones:['Z-OPS'], relevance_type:'Direct',
    implemented_sl:2, target_sl:3, observed_conn:2, allowed_conn:1, purdue_adjacency:1, log_backed:true,
    description:'Pre-auth RCE (BlueKeep) reachable on an exposed RDP service.', source:'ai', ai_confidence:72, status:'Open' },
  { vuln_id:'V-1005', title:'Cleartext control protocol on RTU',
    asset_label:'RTU-FIELD-01', assets:['RTU-FIELD-01'],
    cvss:9.2, epss:0.18, in_kev:false, cwe:'CWE-319', cve_id:'CVE-2021-34526',
    tech:'RTU', protocol:'DNP3', zones:['Z-CTRL'], relevance_type:'Direct',
    implemented_sl:1, target_sl:3, observed_conn:2, allowed_conn:1, purdue_adjacency:1,
    air_gapped:true, log_backed:true,
    description:'Field control commands carried without encryption or authentication. Zone is claimed air-gapped by the client.',
    source:'ai', ai_confidence:78, status:'Open' },
  { vuln_id:'V-1006', title:'Insecure remote firmware update on safety controller',
    asset_label:'SIS-LOGIC-01', assets:['SIS-LOGIC-01'],
    cvss:9.0, epss:0.15, in_kev:false, cwe:'CWE-494', cve_id:'CVE-2022-31206',
    tech:'SIS', zones:['Z-SAF'], relevance_type:'Direct',
    implemented_sl:1, target_sl:4, observed_conn:1, allowed_conn:1, purdue_adjacency:1, log_backed:true,
    description:'The safety logic solver accepts unsigned firmware images over its maintenance interface.',
    source:'ai', ai_confidence:76, status:'Open' },
  { vuln_id:'V-1007', title:'SQL injection in corporate web portal',
    asset_label:'CORP-WEB-01', assets:['CORP-WEB-01'],
    cvss:8.6, epss:0.35, in_kev:false, cwe:'CWE-89', cve_id:'CVE-2023-51467',
    tech:'Web / boundary', zones:['Z-ENT'], relevance_type:'Direct',
    implemented_sl:2, target_sl:2, observed_conn:2, allowed_conn:2, purdue_adjacency:0, log_backed:true,
    internet_facing:true,
    description:'Unsanitised input on the public-facing web portal allows database read/write.',
    source:'ai', ai_confidence:82, status:'Open' },
  { vuln_id:'V-1008', title:'Unauthenticated historian API allows data export',
    asset_label:'HIST-REPL-01', assets:['HIST-REPL-01'],
    cvss:7.8, epss:0.20, in_kev:false, cwe:'CWE-306', cve_id:'CVE-2021-38452',
    tech:'Historian', zones:['Z-DMZ'], relevance_type:'Direct',
    implemented_sl:2, target_sl:3, observed_conn:1, allowed_conn:2, purdue_adjacency:0, log_backed:true,
    description:"The historian replica's REST API returns full process history to any requester on the segment.",
    source:'ai', ai_confidence:69, status:'Open' },
  { vuln_id:'V-1009', title:'Jump host missing network segmentation from OT',
    asset_label:'JUMP-01', assets:['JUMP-01'],
    cvss:7.4, epss:0.28, in_kev:false, cwe:'CWE-923', cve_id:'CVE-2022-29464',
    tech:'Jump host', zones:['Z-DMZ'], relevance_type:'Direct',
    implemented_sl:2, target_sl:3, observed_conn:2, allowed_conn:2, purdue_adjacency:1, log_backed:true,
    description:'The jump host bridges vendor remote-access sessions directly into Operations with no intermediate control.',
    source:'ai', ai_confidence:71, status:'Open' },
  { vuln_id:'V-1010', title:'Relay manager susceptible to resource-exhaustion DoS',
    asset_label:'RELAY-MGR-01', assets:['RELAY-MGR-01'],
    cvss:7.5, epss:0.10, in_kev:false, cwe:'CWE-400', cve_id:'CVE-2020-25159',
    tech:'Relay manager', protocol:'DNP3', zones:['Z-OPS'], relevance_type:'Direct',
    implemented_sl:1, target_sl:3, observed_conn:1, allowed_conn:1, purdue_adjacency:1, log_backed:true,
    description:"A malformed DNP3 request exhausts the relay manager's connection table, halting polling.",
    source:'ai', ai_confidence:64, status:'Open' },
  // ── Inferred: tech/zone-mapped, no confirmed asset ───────────────────────
  { vuln_id:'V-2001', title:'Modbus TCP lacks authentication (protocol class)',
    asset_label:null, cvss:null, epss:0.30, in_kev:false, protocol:'Modbus',
    zones:['Z-CTRL', 'Z-OPS'], relevance_type:'Inferred',
    implemented_sl:1, target_sl:3, observed_conn:2, allowed_conn:2, purdue_adjacency:1, log_backed:true,
    description:'Modbus seen in traffic. The protocol has no native authentication; any device speaking it in these zones is exposed.',
    source:'ai', ai_confidence:60, status:'Open' },
  { vuln_id:'V-2002', title:'Known historian software family vulnerabilities',
    asset_label:null, cvss:7.5, epss:0.12, in_kev:false, cwe:'CWE-89', tech:'Historian',
    zones:['Z-DMZ'], relevance_type:'Inferred',
    implemented_sl:2, target_sl:3, observed_conn:1, allowed_conn:1, purdue_adjacency:0,
    description:'Historian technology present; CVE class applies but the specific asset/version is not yet confirmed.',
    source:'ai', ai_confidence:48, status:'Open' },
  { vuln_id:'V-2003', title:'Exploited VPN appliance flaw relevant to OT edge',
    asset_label:null, cvss:9.1, epss:0.92, in_kev:true, cve_id:'CVE-2023-27997',
    tech:'Jump host', zones:['Z-DMZ'], relevance_type:'Inferred',
    implemented_sl:2, target_sl:3, observed_conn:1, allowed_conn:2, purdue_adjacency:1,
    internet_facing:true,
    description:'Actively exploited SSL-VPN heap overflow. Included as globally relevant even without a confirmed asset map. Appliance is internet-facing.',
    source:'ai', ai_confidence:55, status:'Open' },
  // ── Systemic: non-CVE architectural weaknesses ───────────────────────────
  { vuln_id:'V-3001', title:'Flat OT network — no segmentation within Control zone',
    asset_label:null, systemic:true, zones:['Z-CTRL'], relevance_type:'Systemic',
    exposure_severity:0.9, control_weakness:0.9, implemented_sl:1, target_sl:3,
    observed_conn:3, allowed_conn:3, purdue_adjacency:1, log_backed:true,
    description:'Logs show controllers communicating laterally with no internal boundary. A foothold on any device reaches all.',
    source:'ai', ai_confidence:70, status:'Open' },
  { vuln_id:'V-3002', title:'Weak conduit between OT DMZ and Operations',
    asset_label:null, systemic:true, zones:['Z-OPS'], relevance_type:'Systemic',
    exposure_severity:0.8, control_weakness:0.75, implemented_sl:1, target_sl:3,
    observed_conn:2, allowed_conn:3, purdue_adjacency:1,
    description:'Permissive rules on the DMZ→Operations conduit; broad allowances rather than specific, justified flows.',
    source:'ai', ai_confidence:66, status:'Open' },
  { vuln_id:'V-3003', title:'Insufficient authentication controls across Operations',
    asset_label:null, systemic:true, zones:['Z-OPS'], relevance_type:'Systemic',
    exposure_severity:0.7, control_weakness:0.8, implemented_sl:1, target_sl:3,
    observed_conn:1, allowed_conn:2, purdue_adjacency:0,
    description:'Shared operator logins and absent MFA weaken accountability and access control zone-wide.',
    source:'ai', ai_confidence:62, status:'Open' },
];

export const VULN_SEED = RAW.map(scoreVulnerability).sort((a, b) => b.risk_score - a.risk_score);
